version: "3.9"
services:
    nginx:
        container_name: nginx
        build:
            context: ./dockerfiles
            dockerfile: nginx.dockerfile
        restart: on-failure
        depends_on:
            - php
        ports:
            - "80:80"
        tty: true
        networks:
            - talent
        volumes:
            - ./dockerfiles/storage/logs/nginx/:/var/log/nginx
            - .:/var/www/talent
    php:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - .:/var/www/talent
        networks:
            - talent
    mysql:
        image: mysql:8.0
        container_name: mysql8
        ports:
            - "3306:3306"
        networks:
            - talent
        tty: true
        environment:
            - MYSQL_DATABASE=talent
            - MYSQL_USER=talent
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dockerfiles/storage/data/mysql:/var/lib/mysql
    mailhog:
        container_name: laramail
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - talent
networks:
    talent: